[project]
name = "crimsonslate-tools"
description = "Django project dev tools by crimsonslate"
version = "2.0.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.14"
authors = [
    { name = "Blake Nall", email = "blake@crimsonslate.com" },
    { name = "Kosta Kapatos", email = "kosta@crimsonslate.com" },

]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
dependencies = ["django>=6.0.1"]

[project.urls]
Homepage = "https://github.com/crimsonslate/tools"
Repository = "https://github.com/crimsonslate/tools"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
omit = ["tests/test_*.py"]

[tool.hatch.build.targets.wheel]
packages = ["crimsonslate_tools"]

[tool.pyright]
strictListInference = false
strictDictionaryInference = false
strictSetInference = false
typeCheckingMode = "basic"

[tool.ruff]
indent-width = 4
line-length = 79
target-version = "py314"
exclude = [
    ".git",
    ".gitignore",
    ".venv",
    "venv",
    ".vscode",
    "__pycache__",
    "node_modules",
    "site-packages",
    "dist",
    "build",
]

[tool.ruff.lint]
extend-per-file-ignores = { "*/migrations/*.py" = ["E501"] }
fixable = ["ALL"]
ignore = ["DJ001", "F821"]
unfixable = []
select = ["DJ", "E4", "E7", "E9", "F"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[dependency-groups]
docs = ["coverage>=7.13.3"]
